name: restaurant_web
version: 1.0.0
publish_to: "none"
description: Web pÃºblica multi-tenant para restaurantes (Supertacos MVP)
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.3
  responsive_framework: ^1.1.1
  url_launcher: ^6.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/restoflowlogo.jpg
